name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests (CI job)
        run: echo "Your CI tests would run here"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create CodeDeploy deployment
        run: |
          zip -r acebook-app.zip .
          aws s3 cp acebook-app.zip s3://sumairaa-acebook/acebook-app.zip
          aws deploy create-deployment \
            --application-name sumairaa-application \
            --deployment-group-name sumairaa-deployment \
            --s3-location bucket=sumairaa-acebook,key=acebook-app.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce